Rename the `query` argument labels and attempt to improve the documentation.
sergdort/ReactiveFeedback pull request #23
Opened 2018-05-15 20:09 UTC by andersio

The suggestion here is renaming `query` to `skippingRepeat` and `skippingNil` which are more explicit about the behaviour than the current form.

2018-06-01 15:45 UTC, p4checo commented
Great improvements! 👏 

I was about to open a PR to use `filterMap`'s inside the `init`'s, but then I saw this PR 😆

One suggestion though, shouldn't the `skippingRepeated` variant be `skippingRepeatedAndNil`, since it also skips `nil`'s?

2018-06-01 21:46 UTC, sergdort commented on ReactiveFeedback/Feedback.swift
> +        self.init(deriving: { $0.filterMap(transform).skipRepeats(==) },
This is not the same as `query`. Because previous implementation cancels previous `Effect` when `Control` switches to `nil`

2018-06-01 21:46 UTC, sergdort commented on ReactiveFeedback/Feedback.swift
> +        self.init(deriving: { $0.filterMap(transform) },
same

2018-06-01 21:48 UTC, sergdort commented on ReactiveFeedback/Feedback.swift
> +        self.init(deriving: { $0.filterMap(transform).skipRepeats(==) },
This is actual reason why it's called `Control` because value of the `State` acts as a `Feedback` controller :)

2018-06-01 21:53 UTC, sergdort requested changes
Some stuff is broken 😜

2018-06-14 22:44 UTC, andersio commented on ReactiveFeedback/Feedback.swift
> +                .observe(on: scheduler)
Note to self: 🙅‍♂️

2018-06-16 23:54 UTC, RuiAAPeres commented
Any outcome out of this PR?

2018-06-21 18:37 UTC, andersio commented
@sergdort addressed your comments.

2018-06-21 18:39 UTC, andersio commented
@p4checo 

> One suggestion though, shouldn't the `skippingRepeated` variant be `skippingRepeatedAndNil` (or `skippingNilAndRepeated`), since it also skips nil's?

`nil` is not being skipped over. While it doesn't trigger any new effect on its own, it cancels the outstanding ones.

2018-06-21 21:18 UTC, p4checo commented
@andersio 

> `nil` is not being skipped over. While it doesn't trigger any new effect on its own, it cancels the outstanding ones.

When I made that comment, the `skippingRepeated` variant used a `filterMap`, hence my comment on the `nil`. It no longer applies on your most recent changes though 😉 

For completeness, the old version was:

```swift
    public init<Control: Equatable, Effect: SignalProducerConvertible>(
        skippingRepeated transform: @escaping (State) -> Control?,
        effects: @escaping (Control) -> Effect
    ) where Effect.Value == Event, Effect.Error == NoError {
        self.init(deriving: { $0.filterMap(transform).skipRepeats(==) },
                  effects: effects)
    }
```

Whereas the new one is:

```swift
    public init<Control: Equatable, Effect: SignalProducerConvertible>(
        skippingRepeated transform: @escaping (State) -> Control?,
        effects: @escaping (Control) -> Effect
    ) where Effect.Value == Event, Effect.Error == NoError {
        self.init(deriving: { $0.map(transform) },
                  effects: { $0.map(effects)?.producer ?? .empty })
    }
```

2018-06-27 08:54 UTC, sergdort approved these changes

2018-07-28 14:37 UTC, mluisbrown approved these changes

2018-07-28 15:43 UTC, RuiAAPeres commented
```
        expected to eventually equal <[initial, initial_a, initial_a_b, initial_a_b_a, initial_a_b_a_b]>, got <[initial, initial_a, initial_a_a, initial_a_a_a, initial_a_a_a_a]>
```

2018-07-29 20:36 UTC, andersio commented
The same test is failing on `develop` with Xcode 10 and ReactiveSwift 3.1. It is likely due to the RAS 3.1 constant producer interruption fix, which makes RAF cancel outstanding scheduled work items (effects and events) as expected. 🤔

2018-08-30 10:57 UTC, diegopetrucci commented
How are we planning to fix this?

2018-09-10 20:05 UTC, andersio commented
@diegopetrucci The commit had already been pushed before the comment.

2018-10-06 19:56 UTC, merged